name: news_admin
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 5.0.0+13

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cached_network_image: ^3.2.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.3
  firebase_core: ^1.17.1
  flutter_html: ^2.2.1
  http: ^0.13.3
  intl: ^0.17.0
  line_icons: ^2.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.7
  url_launcher: ^6.1.2
  google_fonts: ^3.0.1
  html_unescape: ^2.0.0
  firebase_auth: ^3.3.19
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:

    - family: THICKCCBOI
      fonts:
        - asset: assets/fonts/THICCCBOI-Light.ttf
          weight: 400
        - asset: assets/fonts/THICCCBOI-Regular.ttf
          weight: 500
        - asset: assets/fonts/THICCCBOI-Medium.ttf
          weight: 600
        - asset: assets/fonts/THICCCBOI-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/THICCCBOI-Bold.ttf
          weight: 800

  assets:

    - assets/images/
